const fs = require('fs-extra');
const path = require('path');

const sitemapSrc = path.join(process.cwd(), 'sitemap-0.xml'); // generated by next-sitemap
const sitemapDest = path.join(process.cwd(), 'public', 'sitemap.xml');

fs.copySync(sitemapSrc, sitemapDest);
console.log('✅ Sitemap copied to public/sitemap.xml');